version: "3.7"

services:

  db:
    build:
      context: ./db 
    container_name: app-stack-db
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=appdbadm
      - POSTGRES_PASSWORD=appdbadm
    ports:
      - 5432:5432

  back:
    build:
      context: ./back
    container_name: app-stack-back
    working_dir: /app
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=appdb
      - POSTGRES_USER=appdbadm
      - POSTGRES_PASSWORD=appdbadm
    volumes:
      - ./back/src:/app
    ports: 
      - "8080:8080"
    depends_on:
      - db
    entrypoint: ['denon', 'run', '--allow-net', '--allow-env', 'index.js']
  
  front:
    build:
      context: ./front
    container_name: app-stack-front
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    

volumes:
  pg-data:
