version: "3.7"

services:

  db:
    image: postgres
    volumes:
      - ./.pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app-stack-db
      - POSTGRES_USER=app-stack-adm
      - POSTGRES_PASSWORD=appstackadm

  deno:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports: 
      - "80:8080"
    # entrypoint: ['deno', 'run', '--allow-net', 'index.js']
    
