version: "3.7"

services:

  deno:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports: 
      - "80:8080"
    # entrypoint: ['deno', 'run', '--allow-net', 'index.js']
    
